export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_ACCEPTED = 'LOGIN_ACCEPTED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const NETWORK_CONNECTIVITY_CONFIRMED = "NETWORK_CONNECTIVITY_CONFIRMED";
export const NO_NETWORK_CONNECTIVITY = "NO_NETWORK_CONNECTIVITY";
export const PROFILE_RECEIVED = "AUTH_CONFIRMED";
export const AUTH_DECLINED = "AUTH_DECLINED";

export const MAIN_PROFILE_MENU_OPENED = "MAIN_PROFILE_MENU_OPENED";
export const MAIN_PROFILE_MENU_CLOSED = "MAIN_PROFILE_MENU_CLOSED";